baseURL = "/"
languageCode = "en-us"
title = "BSD Tools Engineering"
theme = "kube"
description = "The BSD Tools are designed to help you manage and grow inspiring, impactful digital programs—from fundraising to advocacy, communications to analytics. This is how we do it."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Blue State Digital" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "tools@bluestatedigital.com"

[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
